name: test

on:
  push:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependency
        run: sudo apt update && sudo apt install -y gcc
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19.1
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.1
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: go mod download
        run: go mod download
      - name: test
        run: go test ./... 
